apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notes-pvc
  labels:
    app: notes
spec:
  accessModes:
    - ReadWriteOnce        # One node mounts for read/write at a time
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-rwo   # GKE block storage; auto-provisions GCE disk
